name: Release
run-name: ${{ github.actor }} is creating a new release
on:
  workflow_dispatch:
    secrets:
      release_token:
        description: "The release token for this package, which you find at https://foundryvtt.com/packages/better-hexagonal-tiles/edit"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parse module.json
        id: module 
        run: |
          {
            echo 'module<<EOF'
            cat ./module.json
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Zip files
        run: zip -r ./better-hexagonal-tiles.zip ./module ./module.json ./README.md
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./module.json,./better-hexagonal-tiles.zip"
          tag: ${{ fromJson(steps.module.outputs.module).version }}
      - name: Update FoundryVTT
        run: python ./push-to-foundryvtt.py --release_version="${{ secrets.release_token }}"
