name: Release
run-name: ${{ github.actor }} is creating a new release
on:
  workflow_dispatch:
    secrets:
      RELEASE_TOKEN:
        description: "The release token for this package, which you find at https://foundryvtt.com/packages/better-hexagonal-tiles/edit"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parse module.json
        id: module
        run: |
          module="$(cat ./module.json)"
          echo module=$module >> "${GITHUB_OUTPUT}"
      - name: Zip files
        run: zip -r ./better-hexagonal-tiles.zip ./module ./module.json ./README.md
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./module.json,./better-hexagonal-tiles.zip"
          tag: ${{ fromJson(steps.module.outputs.module).version }}
          skipIfReleaseExists: true
      - name: Update FoundryVTT
        run: python ./push-to-foundryvtt.py --release-token='${{ secrets.RELEASE_TOKEN }}'
